# Generated by Django 2.1.4 on 2019-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190309_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
