# Generated by Django 2.1.4 on 2019-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_converter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
