# Generated by Django 2.1.4 on 2019-03-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190309_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converter',
            old_name='slug_title',
            new_name='slug',
        ),
    ]
