# Generated by Django 2.1.4 on 2019-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190309_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='tag_line',
            field=models.TextField(null=True),
        ),
    ]
