# Generated by Django 2.1.4 on 2019-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_converter_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='converter_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
