# Generated by Django 2.1.4 on 2019-03-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_converter_converter_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converter',
            old_name='converter_url',
            new_name='convert_from',
        ),
    ]
