# Generated by Django 2.1.4 on 2019-03-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190310_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
